import Headers from "@/components/layout/Headers";
import "./globals.css";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "Logo Project | Office",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Headers />
        {children}
        <Footer />
      </body>
    </html>
  );
}
